//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsTable
    {
        public int id { get; set; }
        public string carId { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public Nullable<bool> available { get; set; }
    }
}
